// This file is auto-generated by scripts/set-env.js
// Do not edit this file directly. Update .env instead.
// Generated at: 2026-02-25T15:46:04.852Z

export const environment = {
  production: true,
  firebase: {
    apiKey: 'AIzaSyBNvG5OQkJtAMYC-d8t7XUYGe49SOSeDi0',
    authDomain: 'moneyzen-app.firebaseapp.com',
    projectId: 'moneyzen-app',
    storageBucket: 'moneyzen-app.firebasestorage.app',
    messagingSenderId: 'Y425896027562',
    appId: '1:425896027562:web:61046f6b318d2ec019b7d3',
    vapidKey: 'SyCjxmCwhKMljLtsqNc1XdyidwNm2sYzvv6le1OVnUo'
  }
};
