/**
 * Environment Configuration Loader
 *
 * This script reads environment variables from .env file and generates
 * the Angular environment configuration files.
 *
 * Usage:
 *   node scripts/set-env.js
 *
 * Or with npm:
 *   npm run config
 */

const fs = require('fs');
const path = require('path');

// Load .env file
function loadEnvFile(filePath) {
  const envVars = {};

  if (!fs.existsSync(filePath)) {
    console.warn(`⚠️  .env file not found at ${filePath}`);
    console.warn('Using default values. Create a .env file based on .env.example');
    return envVars;
  }

  const fileContent = fs.readFileSync(filePath, 'utf8');
  const lines = fileContent.split('\n');

  lines.forEach(line => {
    // Skip comments and empty lines
    if (line.trim().startsWith('#') || !line.trim()) return;

    const match = line.match(/^([^=]+)=(.*)$/);
    if (match) {
      const key = match[1].trim();
      let value = match[2].trim();

      // Remove quotes if present
      if (
        (value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))
      ) {
        value = value.slice(1, -1);
      }

      envVars[key] = value;
    }
  });

  return envVars;
}

// Generate environment file content
function generateEnvironmentContent(envVars, isProduction = false) {
  const apiKey = envVars.FIREBASE_API_KEY || 'YOUR_FIREBASE_API_KEY';
  const authDomain = envVars.FIREBASE_AUTH_DOMAIN || 'your-project.firebaseapp.com';
  const projectId = envVars.FIREBASE_PROJECT_ID || 'your-project';
  const storageBucket = envVars.FIREBASE_STORAGE_BUCKET || 'your-project.appspot.com';
  const messagingSenderId = envVars.FIREBASE_MESSAGING_SENDER_ID || 'YOUR_SENDER_ID';
  const appId = envVars.FIREBASE_APP_ID || 'YOUR_APP_ID';
  const vapidKey = envVars.FIREBASE_VAPID_KEY || 'YOUR_VAPID_PUBLIC_KEY';

  return `// This file is auto-generated by scripts/set-env.js
// Do not edit this file directly. Update .env instead.
// Generated at: ${new Date().toISOString()}

export const environment = {
  production: ${isProduction},
  firebase: {
    apiKey: '${apiKey}',
    authDomain: '${authDomain}',
    projectId: '${projectId}',
    storageBucket: '${storageBucket}',
    messagingSenderId: '${messagingSenderId}',
    appId: '${appId}',
    vapidKey: '${vapidKey}'
  }
};
`;
}

// Main function
function main() {
  console.log('🔧 Loading environment configuration...\n');

  const envPath = path.join(__dirname, '..', '.env');
  const envVars = loadEnvFile(envPath);

  // Check if required variables are present
  const requiredVars = ['FIREBASE_API_KEY', 'FIREBASE_PROJECT_ID', 'FIREBASE_VAPID_KEY'];

  const missingVars = requiredVars.filter(
    varName => !envVars[varName] || envVars[varName].startsWith('YOUR_')
  );

  if (missingVars.length > 0) {
    console.warn('⚠️  The following Firebase variables are not configured:');
    missingVars.forEach(v => console.warn(`   - ${v}`));
    console.warn('\nUpdate your .env file with real values from Firebase Console.\n');
  } else {
    console.log('✅ All required environment variables found\n');
  }

  // Generate environment files
  const environmentsDir = path.join(__dirname, '..', 'src', 'environments');

  // Ensure directory exists
  if (!fs.existsSync(environmentsDir)) {
    fs.mkdirSync(environmentsDir, { recursive: true });
  }

  // Generate environment.ts (development)
  const devContent = generateEnvironmentContent(envVars, false);
  fs.writeFileSync(path.join(environmentsDir, 'environment.ts'), devContent);
  console.log('📝 Generated: src/environments/environment.ts');

  // Generate environment.prod.ts (production)
  const prodContent = generateEnvironmentContent(envVars, true);
  fs.writeFileSync(path.join(environmentsDir, 'environment.prod.ts'), prodContent);
  console.log('📝 Generated: src/environments/environment.prod.ts');

  console.log('\n✨ Environment configuration updated successfully!\n');
}

main();
